#测试环境配置
spring:
  profiles: test
  #自定义配置属性
  #视图配置
  mvc:
    static-path-pattern: /static/**
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://localhost:3306/lzhpo-shiro?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    maximum-pool-size: 30