#开发环境配置
spring:
  profiles: dev
  #自定义配置属性
  #视图配置
  mvc:
    static-path-pattern: /static/**
  aop:
    proxy-target-class: true
  datasource:
      url: jdbc:mysql://localhost:3306/lijin?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 30
      type: com.alibaba.druid.pool.DruidDataSource
        #   数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
  redis:
    host: localhost
    port: 6379
    max-wait: 30000
    max-active: 100
    max-idel: 20
    min-idel: 0

